# Generated by Django 6.0.6 on 2026-06-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.ImageField(blank=True, default='watch_default.jpg', upload_to='watches/'),
        ),
    ]
