# Generated by Django 6.0.6 on 2026-06-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=20)),
                ('summ', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], decimal_places=2, max_digits=10)),
            ],
        ),
    ]
