# Generated by Django 6.0.6 on 2026-06-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_image_alter_menu_category_alter_menu_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, default='menu_default.jpg', upload_to='menus/'),
        ),
    ]
