# Generated by Django 6.0.6 on 2026-06-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='image',
            field=models.ImageField(default='chef_default', upload_to='chefs/'),
        ),
    ]
