# Generated by Django 6.0.6 on 2026-06-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chef_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
                ('clients', models.IntegerField()),
                ('awards', models.IntegerField()),
                ('events', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=models.ImageField(blank=True, default='chef_default.png', upload_to='chefs/'),
        ),
    ]
