# Generated by Django 6.0.6 on 2026-06-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('info', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, default='furniture_default', upload_to='media/furniture/')),
                ('category', models.CharField(choices=[('sofas', 'Sofas'), ('lights', 'Lights'), ('tables', 'Tables'), ('beds', 'Beds'), ('chairs', 'Chairs')], max_length=30)),
            ],
        ),
    ]
