# Generated by Django 6.0.6 on 2026-06-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='image',
            field=models.ImageField(blank=True, default='furniture_default.jpg', upload_to='furniture/'),
        ),
    ]
